# Generated by Django 5.1.4 on 2025-01-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='readers',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='Enginering Book'),
            preserve_default=False,
        ),
    ]
