name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker-compose -f docker-compose.yml build

      - name: Run pre-commit hooks in Docker container
        run: |
          docker-compose -f docker-compose.yml run --rm web pre-commit install
          docker-compose -f docker-compose.yml run --rm web pre-commit run --all-files

  tests:
    runs-on: ubuntu-latest
    needs: precommit
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker-compose -f docker-compose.yml build

      - name: Run DB Migrations
        run: |
          docker-compose -f docker-compose.yml run --rm web python manage.py migrate

      - name: Run Django Tests with Coverage
        run: |
          docker-compose -f docker-compose.yml run --rm web coverage run -m pytest books/tests.py reviews/tests.py users/tests.py
          docker-compose -f docker-compose.yml run --rm web coverage report

      - name: Check coverage percentage
        run: |
          coverage report --fail-under=80
          
      - name: Tear down the Stack
        run: |
          docker-compose -f docker-compose.yml down
